name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Remotion Release"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - name: get remotion version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./container/package.json"
          prop_path: "version"

      - run: echo version pulled from package.json":" "${{ steps.version.outputs.prop }}"

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/1079363441639/locations/global/workloadIdentityPools/github-id-pool/providers/github-provider
          service_account: github-action@remotion-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: ./container
          push: true
          tags: |
            us-docker.pkg.dev/remotion-dev/cloud-run/render:${{ steps.version.outputs.prop }}
            us-docker.pkg.dev/remotion-dev/cloud-run/render:latest
