name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  docker-release:
    runs-on: ubuntu-latest
    ## if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') # <-- Filtering to only run when a tagged commit is pushed

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/1079363441639/locations/global/workloadIdentityPools/github-id-pool/providers/github-provider
          service_account: github-action@remotion-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        # run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        # run: echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        run: echo "short_ref=4.0.1" >> $GITHUB_OUTPUT

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: ./container
          push: true
          tags: |
            us-docker.pkg.dev/remotion-dev/cloud-run/render:${{ steps.get-tag.outputs.short_ref }}
            us-docker.pkg.dev/remotion-dev/cloud-run/render:latest
